/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TourRouteImport } from './routes/tour'
import { Route as CraftIndexRouteImport } from './routes/craft/index'
import { Route as CraftSlugRouteImport } from './routes/craft/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TourRoute = TourRouteImport.update({
  id: '/tour',
  path: '/tour',
  getParentRoute: () => rootRouteImport,
} as any)
const CraftIndexRoute = CraftIndexRouteImport.update({
  id: '/craft/',
  path: '/craft/',
  getParentRoute: () => rootRouteImport,
} as any)
const CraftSlugRoute = CraftSlugRouteImport.update({
  id: '/craft/$slug',
  path: '/craft/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tour': typeof TourRoute
  '/craft/$slug': typeof CraftSlugRoute
  '/craft/': typeof CraftIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tour': typeof TourRoute
  '/craft/$slug': typeof CraftSlugRoute
  '/craft': typeof CraftIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tour': typeof TourRoute
  '/craft/$slug': typeof CraftSlugRoute
  '/craft/': typeof CraftIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/tour' | '/craft/$slug' | '/craft/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/tour' | '/craft/$slug' | '/craft'
  id: '__root__' | '/' | '/tour' | '/craft/$slug' | '/craft/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TourRoute: typeof TourRoute
  CraftSlugRoute: typeof CraftSlugRoute
  CraftIndexRoute: typeof CraftIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tour': {
      id: '/tour'
      path: '/tour'
      fullPath: '/tour'
      preLoaderRoute: typeof TourRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/craft/': {
      id: '/craft/'
      path: '/craft'
      fullPath: '/craft/'
      preLoaderRoute: typeof CraftIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/craft/$slug': {
      id: '/craft/$slug'
      path: '/craft/$slug'
      fullPath: '/craft/$slug'
      preLoaderRoute: typeof CraftSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TourRoute: TourRoute,
  CraftSlugRoute: CraftSlugRoute,
  CraftIndexRoute: CraftIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
